[package]
name = "manifold_hangman"
version = "0.1.0"
edition = "2024"

[dependencies]
rand_core = "0.10.0"
rand_chacha = "0.10.0"
toml = "0.9.8"
serde = { version = "1.0", features = ["derive"] }
regex = "1.10"
anyhow = "1.0.100"