evil_exponent = 2.0
evil_factor = 1.5
word_list_path = "words.txt"
exclusions_list_path = "exclusions.txt"
salt_file_path = "salts/testing_salt.toml"
history_path = "histories/testing_history.toml"
verbose = true